### ISSUE TITLE
找不到type字段

### ISSUE THREAD

**Issue by Mr-ShiHuaYu** [wenhainan/thinkphp6-auth#1]
不知道更新后有没有更新sql的建表语句呢?
我使用的时候发生了在auth_rule表里面找不到type列的情况,查看sql,也可以看到,根本没有type这个字段
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'where clause'`
`//读取用户组所有权限规则
        $rules = Db::name($this->config['auth_rule'])->where($map)->field('condition,name')->select();`

**Comment by wenhainan** [comment]
readme.md文件更新了,你可以重新生成下数据表.

**Comment by Mr-ShiHuaYu** [comment]
> readme.md文件更新了,你可以重新生成下数据表.

那么,type是什么意思呢?备注里面没有说明,还没看源码 @wenhainan

**Comment by wenhainan** [comment]
支持规则表达式。
在auth_rule 表中定义一条规则时，如果type为1， condition字段就可以定义规则表达式。 如定义{score}>5  and {score}<100  表示用户的分数在5-100之间时这条规则才会通过。
这个功能很少人用.

**Comment by Mr-ShiHuaYu** [comment]
但是,我看老版本的意思是,如果condition字段有值,才会开始判断condition字段,否则,不考虑condition,为什么还要添加一个字段呢?是否多余?

**Comment by wenhainan** [comment]
感谢大佬建议,这周末我再继续完善下此仓库,文档和代码更清晰点.

**Comment by Mr-ShiHuaYu** [comment]
好的,谢谢

**Comment by leinstein** [comment]
thinkphp6.0.10 mysql5.7 第一次验证得2秒，你们是不是这样子
