### ISSUE TITLE
权限分组问题

### ISSUE THREAD

**Issue by chao1991528** [wenhainan/thinkphp6-auth#2]
为什么auth类的方法getGroups获取的分组是多个，而方法getRole获取的权限却只有一个？这不就矛盾了，一个用户可以有多个分组，却只能显示一个分组

**Comment by wenhainan** [comment]
> 为什么auth类的方法getGroups获取的分组是多个，而方法getRole获取的权限却只有一个？这不就矛盾了，一个用户可以有多个分组，却只能显示一个分组

有新的想法，可以提个PR，我合并下
